### PR TITLE
C++ 14 & Student, Teacher, Assignment, Grade Unit tests

### PR DESCRIPTION
**Pull request by andrewlod**
Hello!

I have added the following features in this PR:
- Unit test fixtures
- Unit tests for the following functionalities of Student, Teacher, Assignment and Grade:
  - Load data
  - Save data
  - Print data
  - Query one
  - Query many
- Changed default C++ version from C++11 to C++14
  - GoogleTest requires C++ 14, plus at some point we might use `std::make_unique`

Build instructions remain the same.

### CODE REVIEW

**Comment by andrewlod** [comment]
I have also forgot to mention:
- Fixed instances where GBResourceNotFound was thrown and `resourceId` was not passed, as this parameter is now required since last update.

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge 

The new structure changes look good

The tests pass.

Approving this PR for merge and merging

Thanks  for the opportunity to review your PR and for your contributions :-)

I would like to recommend and request we do at least one Valgrind test on the codebase soon.

Code formatting issues have been resolved.  Need to investigate clang tidy clang format and some other helpful configuration files.

Approving this PR for merge and merging.

**Comment by andrewlod** [comment]
> I would like to recommend and request we do at least one Valgrind test on the codebase soon.

I will work on that soon. Not sure if the best approach is to use Valgrind on unit tests or having it as an option of the actual runtime of the program.

**Comment by gbowne1** [comment]
I have not had much experience with Valgrind except that Ive been made aware that it is very good at memory leak detection as well as other things. I don't expect any memory leaks but hard to say without testing and its not much of a concern yet without terribly much completeness yet.

I dont know how good CTest or Google Test is at memory leak detection and other 

I will note that I won't be able to use Google Test on my older development VM as its repo only has 3.13.  Its based on Debian 10 Buster.
I would have to download from the Ubuntu 20.04 repo and adding the Ubuntu kitware repo and its keys if not having to build from source which is ok.

**Pull request merged**
