### PR TITLE
[Feature] adding a basic report card generator

### PR DESCRIPTION
**Pull request by gbowne1**
This is adding a basic report and/or report card generator.

This implementation is not finished, just wanted to get some initial work in. It should not take much to get it working and it might have to get added into main.cpp and gradebook.cpp/gradebook.h as well but don't know what that code might look like just yet.  Will entertain ideas on that.

### CODE REVIEW

**Review by andrewlod — APPROVED** [review]
Looks good! Approving.

Thank you for the PR!

**Comment by gbowne1** [comment]
@andrewlod 

I just figured I would get something in while I was thinking about it.  There's some small things I want to add, even if they aren't totally finished.  One of us will eventually get to finish implementing.

**Comment by andrewlod** [comment]
@gbowne1 

Sounds good! Last days have been a bit hectic so I wasn't able to contribute, but in the next few days I will probably implement either Valgrind or documentation

**Comment by gbowne1** [comment]
no worries @andrewlod.  I figured you were busy.  I have been a bit busy too.

**Pull request merged**
